name: Matrix Demo
on:
  - workflow_dispatch
  - push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        runner: [ubuntu-latest, windows-latest]
        include:
            - node-version: 18
              runner: ubuntu-latest
        exclude:
            - node-version: 12
              runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
