name: Matrix Demo
on:
  - workflow_dispatch
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install node js
        uses: setup-node@v3
        with:
          node-version: 18
      - name: Cache Depencies
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build project
        run: npm run build
